language: objective-c

branches:
  only:
    - master

xcode_project: Permission.xcodeproj
xcode_scheme: PermissionTests
osx_image: xcode10.2
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild test -project Permission.xcodeproj -scheme PermissionTests -destination "platform=iOS Simulator,name=iPhone XR"
